### ISSUE TITLE
Progress over 100% - use gradient?

### ISSUE THREAD

**Issue by inPhilly** [skywinder/GaugeKit#36] opened 2016-07-24 18:20 UTC
This works perfectly for progress up to 100%. Then, it become indistinguishable from the first go-around. Is there a way to add a gradient based on progress, so that once the progress is over 100%, the gradient looks different than the gradient is overlapping, and the user can see their actual progress?

**Comment by skywinder** [comment] 2016-07-25 12:44
@mommyme Hello. Thanks for request. I agree, it's must have feature.
It's kind of duplicate of #12. I will implement this feature in next release for sure!

**Closed as completed by skywinder** 2016-07-25 12:44 UTC
Labels: duplicate, enhancement
